spring:
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}


    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        open-in-view: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                show-sql: true
                format_sql: true
                highlight_sql: true
                use_sql_comments: true

    springdoc:
        swagger-ui:
            path: /swagger-ui.html
            groups-order: DESC
            operationsSorter: method
            disable-swagger-default-url: true
            display-request-duration: true
            defaultModelsExpandDepth: -1
        api-docs:
            path: /api
            show-actuator: true
        default-consumes-media-type: application/json
        default-produces-media-type: application/json
        paths-to-match:
            - /**

jwt:
    secret: ${JWT_SECRET}
